### PR TITLE
[Issue #18] Added element to show a no more results message

### PR DESCRIPTION
**Pull request by ghost**
This adds a p html tag showing a message when the response returns no results. I tried to make the spinner element to be the one that shows the messages,  but that seems to break the component.
Maybe it still needs some style to center the element.

### CODE REVIEW

**Comment by klarkc** [comment]
Something seems to break the tests, needs to be reviewed

**Review by klarkc — CHANGES_REQUESTED** [review]
Could you add some tests to this? Just to check if the text "No more results" is shown when it must have to be shown

**Comment by EMCM** [comment]
Do you know of a way to test DOM elements attributes without using chai-jquery?

**Comment by ghost** [comment]
Can you please help me here? This is new territory for me. Should i write a test for each service? And how my tests will be notified that the message is being shown?

**Comment by klarkc** [comment]
@EMCM look at https://www.polymer-project.org/1.0/docs/tools/tests

The tests are already in place (test/streaming-list-common.html), the tests in this file are executed twice, for each service. You will just have to write a new test function and use assert (chai) to test things.

You can add an event listener, there are streaming-list-response and streaming-list-ready events that can be useful to do this.

**Review by klarkc — APPROVED** [review]

**Pull request merged**
